export const arenas = [
  {
    id: 3,
    title: "Kingz villa",
    type: "Swiss",
    status: "Watchlist",
    players: "3/10",
    duration: "30 mins",
    prize: "Prize",
    visibility: "Public",
    mode: "Traditional",
    entry: "Free for all",
    date: "12th June, 2024",
    creator: "Usman Mustapha",
    profile: {
      username: "king.usman",
      playerId: "KV3902Z",
      rank: "Knight",
      joined: "2nd Jan, 2022, 10:00am",
      avatar: "/images/usman-avatar.jpg",
    },
    abuseHistory: [
      {
        type: "Spamming",
        date: "02-05-2024 14:22:10",
        reporter: "Ali G",
        action: "Muted",
      },
    ],
  },
  {
    id: 1,
    title: "Musa Knight",
    type: "Round Robin",
    status: "Abuse Report",
    players: "8/12",
    duration: "45 mins",
    prize: "₦50,000",
    visibility: "Public",
    mode: "Blitz",
    entry: "Invite Only",
    date: "19th July, 2024",
    creator: "Adeola Benson",
    profile: {
      username: "fedo.mo9",
      playerId: "SH7789JJ",
      rank: "Knight",
      joined: "24th July, 2010, 12:45pm",
      avatar: "/images/musa-avatar.jpg",
    },
    abuseHistory: [
      {
        type: "Cussing",
        date: "17-09-2024 01:25:17",
        reporter: "Fedo",
        action: "Avatar removed",
      },
      {
        type: "Cussing",
        date: "17-09-2024 01:25:17",
        reporter: "Fedo",
        action: "Ignored",
      },
      {
        type: "Cussing",
        date: "17-09-2024 01:25:17",
        reporter: "Fedo",
        action: "Issued warning",
      },
      {
        type: "Cussing",
        date: "17-09-2024 01:25:17",
        reporter: "Fedo",
        action: "Added to watchlist",
      },
    ],
  },
  {
    id: 2,
    title: "Chessyard Royale",
    type: "Round Robin",
    status: "Abuse Report",
    players: "6/12",
    duration: "1 hr",
    prize: "Cash Reward",
    visibility: "Public",
    mode: "Traditional",
    entry: "Invite only",
    date: "14th July, 2024",
    creator: "Esther James",
    profile: {
      username: "queen.ejay",
      playerId: "CR1090L",
      rank: "Rook",
      joined: "15th March, 2021, 3:30pm",
      avatar: "/images/esther-avatar.jpg",
    },
      abuseHistory: [
      {
        type: "Cussing",
        date: "17-09-2024 01:25:17",
        reporter: "Fedo",
        action: "Avatar removed",
      },
      {
        type: "Cussing",
        date: "17-09-2024 01:25:17",
        reporter: "Fedo",
        action: "Ignored",
      },
      {
        type: "Cussing",
        date: "17-09-2024 01:25:17",
        reporter: "Fedo",
        action: "Issued warning",
      },
      {
        type: "Cussing",
        date: "17-09-2024 01:25:17",
        reporter: "Fedo",
        action: "Added to watchlist",
      },
    ],
  },
  {
    id: 4,
    title: "Battle Square",
    type: "Knockout",
    status: "Vulgarity Filter",
    players: "12/12",
    duration: "45 mins",
    prize: "Trophy",
    visibility: "Public",
    mode: "Blitz",
    entry: "Free for all",
    date: "9th May, 2024",
    creator: "Samuel Ade",
    profile: {
      username: "s4mmy",
      playerId: "BS5044X",
      rank: "Bishop",
      joined: "10th Oct, 2020, 5:00pm",
      avatar: "/images/samuel-avatar.jpg",
    },
    abuseHistory: [
      {
        type: "Unsportsmanlike",
        date: "05-06-2024 09:45:00",
        reporter: "Janet",
        action: "Suspended for 1 day",
      },
    ],
  },
  {
    id: 5,
    title: "Mind Clash",
    type: "Arena",
    status: "Blacklist",
    players: "5/8",
    duration: "20 mins",
    prize: "Medal",
    visibility: "Private",
    mode: "OTB",
    entry: "Restricted",
    date: "1st August, 2024",
    creator: "Fatima Bello",
    profile: {
      username: "fatibee",
      playerId: "MC8484T",
      rank: "Pawn",
      joined: "8th August, 2018, 1:15pm",
      avatar: "/images/fatima-avatar.jpg",
    },
    abuseHistory: [
      {
        type: "Cussing",
        date: "04-08-2024 08:30:00",
        reporter: "Zainab",
        action: "Muted",
      },
      {
        type: "Spamming",
        date: "05-08-2024 13:00:00",
        reporter: "Musa",
        action: "Blocked temporarily",
      },
    ],
  },
];

