import Header from "./components/header/page";
import Sidebar from "./components/sidebar/page";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen overflow-hidden">
        <div className="h-[60px] w-full">
          <Header />
        </div>

        <div className="flex h-[calc(100vh-60px)]">
          <div className="w-[15%] h-full">
            <Sidebar />
          </div>

          <div className="w-[85%] h-full overflow-auto bg-gray-100">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}

