export const tableData = [
  {
    subscriptionName: 'Pawn',
    price: '$4.99',
    status: 'Active',
    subscriptionUnit: 'Years',
    subscriptionLength: 2,
    features: 'Event upload: 5 per day, Keens: No access, Ads: 2 per month, Ads: Unlimited',
  },
  {
    subscriptionName: 'Knight',
    price: '$4.99',
    status: 'Active',
    subscriptionUnit: 'Months',
    subscriptionLength: 70,
    features: 'Event upload: 5 per day, Keens: Unlimited, Ads: 2 per month, Ads: Unlimited',
  },
  {
    subscriptionName: 'King',
    price: '$4.99',
    status: 'Inactive',
    subscriptionUnit: 'Month',
    subscriptionLength: 20,
    features: 'Event upload: 2 per month, Keens: No access, Ads: 2 per month, Ads: Unlimited',
  },
  {
    subscriptionName: 'Pawn',
    price: '$4.99',
    status: 'Inactive',
    subscriptionUnit: 'Days',
    subscriptionLength: 300,
    features: 'Event upload: 5 per day, Keens: Unlimited, Ads: 2 per month, Ads: Unlimited',
  },
  {
    subscriptionName: 'Pawn',
    price: '$4.99',
    status: 'Active',
    subscriptionUnit: 'Days',
    subscriptionLength: 500,
    features: 'Event upload: 6 per week, Keens: No access, Ads: 2 per month, Ads: Unlimited',
  },
  {
    subscriptionName: 'Pawn',
    price: '$4.99',
    status: 'Inactive',
    subscriptionUnit: 'Months',
    subscriptionLength: 10,
    features: 'Event upload: 6 per week, Keens: No access, Ads: 2 per month, Ads: Unlimited',
  },
  {
    subscriptionName: 'Pawn',
    price: '$4.99',
    status: 'Active',
    subscriptionUnit: 'Year',
    subscriptionLength: 4,
    features: 'Event upload: 9 per day, Keens: 2 per week, Ads: 2 per month, Ads: Unlimited',
  },
];